
wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [90, 30, 100]
    rows: [14, 13, 13, 9]
  refreshInterval: 1
  mods:
    # GIT
    gitstatus-platform:
      title: "Git Status - platform"
      type: git
      commitCount: 10
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 0
        left: 0
        height: 1
        width: 2
      refreshInterval: 8
      repositories:
      - "/Users/mitch/Dev/titanhire/titanhire-platform"
    gitstatus-services:
      title: "Git Status - services"
      type: git
      commitCount: 10
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 2
      refreshInterval: 8
      repositories:
      - "/Users/mitch/Dev/titanhire/suited-services"
    # GITHUB
    github-platform:
      type: github
      title: "GH Platform"
      apiKey: "e37afcdb9cb6651c6ec7f38366dada835f8e34fb"
      baseURL: ""
      enabled: true
      enableStatus: true
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 300
      repositories:
        titanhire-platform: "TitanHire"
      uploadURL: ""
      username: "newtmitch"
    github-services:
      type: github
      title: "GH Services"
      apiKey: "e37afcdb9cb6651c6ec7f38366dada835f8e34fb"
      baseURL: ""
      enabled: true
      enableStatus: true
      position:
        top: 1
        left: 2
        height: 1
        width: 2
      refreshInterval: 300
      repositories:
        suited-services: "TitanHire"
      uploadURL: ""
      username: "newtmitch"
    # CircleCI
    circleci:
      apiKey: "b1c34a555f5e363b5441618959269820df7e7a8d"
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
    refreshInterval: 30
    # Heroku
    cmdrunner:
      args: ["pipelines:diff", "-a", "wsp-dev"]
      cmd: "heroku"
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      refreshInterval: 30
    # Clock
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      timeFormat: 15:04:05 MST 2006
      locations:
        # From https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        UTC: "Etc/UTC"
        New York: "America/New York"
        Austin: "America/Chicago"
        Los Angeles: "America/Los Angeles"
      position:
        top: 3
        left: 2
        height: 1
        width: 1
      refreshInterval: 10
      # Valid options are: alphabetical, chronological
      sort: "chronological"